name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build project
        run: npm run build
        
      - name: List build files
        run: ls -la dist
        
      - name: Verify build output
        run: |
          echo "Build directory contents:"
          ls -la dist
          echo "Checking index.html:"
          cat dist/index.html
          echo "Checking assets:"
          ls -la dist/assets
          echo "Checking main.js:"
          cat dist/assets/main.*.js
          echo "Full directory tree:"
          tree dist
          echo "Checking file permissions:"
          ls -l dist
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
          enable_jekyll: false
          keep_files: true
          verbose: true
          cname: lista-compras-01.fbiluoficial.github.io
